handle: llm_command
llm-clients:
  - provider: openai
    options:
      api_key: env.OPENAI_API_KEY
      model: gpt-4o-mini

commands:
  pr-ci-test:
    description:
      PR CI test command.
    instructions:
      - applyTo: '**/*'
        modifiedOnly: false
        prompt: |
          Provide a short summary of the changes in this PR in bullet points.

  review-database-schema:
    description:
      Reviews database schema files for consistency, normalization, and naming
      conventions.
    instructions:
      - applyTo: 'examples/sql-database/**/*.sql'
        modifiedOnly: true # Default: true - only review files modified in PR
        prompt: |
          Review this SQL schema definition. Check for normalization, naming conventions, and indexing.
          Suggest improvements or raise warnings if there are any anti-patterns.
        files:
          - path: 'guidelines/db-schema-style.md'
            name: 'Database schema guidelines'

  review-graphql-schema:
    description:
      Reviews GraphQL schema files for consistency and best practices.
    instructions:
      - applyTo: 'examples/graphql-blog/**/*.graphql'
        prompt: |
          Review this GraphQL schema file against the provided style and naming guidelines.
          Highlight any issues and suggest improvements using code diffs.
        files:
          - path: 'https://github.com/mahwy/llm-command-action/blob/main/examples/guidelines/graphql-style.md'
            name: 'GraphQL style guide'

  summarize-pr-comments:
    description: Summarizes the PR comments.
    instructions:
      - prompt: |
          Summarize the comments in this pull request at the time of the command execution.
          Highlight key concerns, decisions, and remaining open questions in bullet points.

  update-changelog:
    description:
      Updates or creates the CHANGELOG.md file based on changes in the pull
      request.
    instructions:
      - applyTo: 'examples/auth-api/**/*'
        prompt: |
          Based on the code changes and PR title and description, generate or update an entry in CHANGELOG.md.
          Maintain consistent formatting and group changes by type (e.g., Feature, Fix, Docs).
        files:
          - path: 'auth-api/CHANGELOG.md'
          - path: 'https://github.com/mahwy/llm-command-action/blob/main/examplesguidelines/changelog-format.md'
            name: 'Changelog formatting template'

  review-typescript-code:
    description:
      Reviews TypeScript code for best practices, type safety, and potential
      issues.
    instructions:
      - applyTo: 'examples/auth-api/**/*.ts'
        modifiedOnly: true # Only review TypeScript files modified in this PR
        prompt: |
          Review this TypeScript code for:
          - Type safety and proper TypeScript usage
          - Code structure and organization
          - Potential bugs or security issues
          - Best practices and conventions
          Provide specific suggestions for improvement.
