/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

import type { Image, Audio, Pdf, Video } from "@boundaryml/baml"
/**
 * Recursively partial type that can be null.
 *
 * @deprecated Use types from the `partial_types` namespace instead, which provides type-safe partial implementations
 * @template T The type to make recursively partial.
 */
export type RecursivePartialNull<T> = T extends object
    ? { [P in keyof T]?: RecursivePartialNull<T[P]> }
    : T | null;

export interface Checked<T,CheckName extends string = string> {
    value: T,
    checks: Record<CheckName, Check>,
}

export interface Check {
    name: string,
    expr: string
    status: "succeeded" | "failed"
}

export function all_succeeded<CheckName extends string>(checks: Record<CheckName, Check>): boolean {
    return get_checks(checks).every(check => check.status === "succeeded")
}

export function get_checks<CheckName extends string>(checks: Record<CheckName, Check>): Check[] {
    return Object.values(checks)
}
export interface Command {
  name: string
  description: string
  instructions: CommandInstruction
  
}

export interface CommandInstruction {
  applyTo?: string | null
  prompt: string
  files: CommandReferenceFile[]
  modifiedOnly?: boolean | null
  
}

export interface CommandOuputInPullRequest {
  command: string
  pull_request_comment: string
  summary: string
  
}

export interface CommandPlan {
  name: string
  loadFiles: LoadFileIntoContext[]
  loadCommandOutputs: LoadCommandOutputIntoContext[]
  
}

export interface CommandReferenceFile {
  name?: string | null
  path: string
  
}

export interface Comment {
  author: string
  body: string
  
}

export interface File {
  name?: string | null
  path: string
  content: string
  patch?: string | null
  
}

export interface LoadCommandOutputIntoContext {
  reason: string
  commandName: string
  
}

export interface LoadDirectoryStructure {
  purpose: string
  type: "directory-structure"
  
}

export interface LoadFileIntoContext {
  reason: string
  fullContent: boolean
  path: string
  
}

export interface LoadPullRequestComments {
  purpose: string
  type: "pr-comments"
  
}

export interface LoadPullRequestDescription {
  purpose: string
  type: "pr-description"
  
}

export interface LoadPullRequestFiles {
  purpose: string
  type: "pr-files"
  includeNumberOfLines: boolean
  includeFileSize: boolean
  includeDiff: boolean
  
}

export interface LoadPullRequestTitle {
  purpose: string
  type: "pr-title"
  
}

export interface PlanResult {
  plans: CommandPlan[]
  
}

export interface PullRequest {
  title: string
  body: string
  comments: Comment[]
  
}

export interface PullRequestCommentForPlan {
  author: string
  body: string
  
}

export interface PullRequestFileForPlan {
  filename: string
  status: "added" | "modified" | "removed" | "renamed"
  
}

export interface PullRequestForPlan {
  title: string
  body: string
  comments: PullRequestCommentForPlan[]
  files: PullRequestFileForPlan[]
  
}

export interface ReadPlannResult {
  pullRequestContextItemsToLoad: (LoadPullRequestTitle | LoadPullRequestDescription | LoadPullRequestComments | LoadPullRequestFiles | LoadDirectoryStructure)[]
  
}

export type PullRequestContextItem = LoadPullRequestTitle | LoadPullRequestDescription | LoadPullRequestComments | LoadPullRequestFiles | LoadDirectoryStructure
